In [21]:
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd
import numpy as np
from sklearn.metrics import precision_score, recall_score, accuracy_score

In [22]:
filename = "iris.data"
df = pd.read_csv(filename)

In [23]:
from sklearn.preprocessing import LabelEncoder
LE = LabelEncoder()
for i in range(len(df.dtypes)):
    if df.dtypes[i] == 'object':
        LE.fit_transform(df[list(df.columns)[i]])
        df[list(df.columns)[i]] = LE.transform(df[list(df.columns)[i]])

In [24]:
# print(df)
data = df.values
# print(data)

x = data[:,:-1]
y = data[:,-1]

In [25]:
model = KNeighborsClassifier(n_neighbors=3)
model.fit(x,y)

# y_pred = model.predict(x)
# print(y_pred)

KNeighborsClassifier(n_neighbors=3)

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size= 0.25, random_state = 42)

# print(X_train.shape)
# print(y_train.shape)
# print(X_test.shape)
# print(y_test.shape)

In [27]:
model.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [28]:
y_pred = model.predict(X_test)

In [29]:
model = KNeighborsClassifier(n_neighbors=3, weights='distance')
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [30]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[15  0  0]
 [ 0  9  2]
 [ 0  1 11]]
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00        15
         1.0       0.90      0.82      0.86        11
         2.0       0.85      0.92      0.88        12

    accuracy                           0.92        38
   macro avg       0.92      0.91      0.91        38
weighted avg       0.92      0.92      0.92        38



In [31]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [32]:
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score

model = MLPClassifier(hidden_layer_sizes=(30, 50, 20), batch_size=10, activation='tanh', max_iter=100)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
acc_score = accuracy_score(y_pred, y_test)

print(classification_report(y_pred,  y_test))

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00        15
         1.0       0.91      0.91      0.91        11
         2.0       0.92      0.92      0.92        12

    accuracy                           0.95        38
   macro avg       0.94      0.94      0.94        38
weighted avg       0.95      0.95      0.95        38



In [33]:
X_train = np.asarray(X_train)
y_train = np.asarray(y_train)

In [34]:
from tensorflow.keras.utils import to_categorical
# y_train = to_categorical(y_train)
print(y_train[:2])

[0. 0.]


In [35]:
from tensorflow.keras import layers
from tensorflow.keras import models
 
model = models.Sequential()
model.add(layers.Dense(16, activation = 'relu'))
model.add(layers.Dense(32, activation = 'relu'))
model.add(layers.Dense(3, activation = 'softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics = ['accuracy'])

In [36]:
# model.fit(X_train, y_train, epochs=100, batch_size=10, verbose=2)

In [38]:
from sklearn import svm
svm_classifier = svm.SVC(kernel='linear', C=100)

svm_classifier.fit(X_train, y_train)

y_pred_svm = svm_classifier.predict(X_test)
print('predict:\n', y_pred_svm)
print('y_true:\n', y_test)

acc_score_svm = accuracy_score(y_pred_svm, y_test)
print('accuracy:\n', acc_score_svm)


predict:
 [1. 0. 2. 1. 2. 0. 1. 2. 1. 2. 2. 0. 0. 0. 0. 1. 2. 2. 1. 2. 0. 2. 0. 2.
 2. 2. 2. 2. 0. 0. 0. 0. 1. 0. 0. 2. 1. 0.]
y_true:
 [1. 0. 2. 1. 1. 0. 1. 2. 1. 1. 2. 0. 0. 0. 0. 1. 2. 1. 1. 2. 0. 2. 0. 2.
 2. 2. 2. 2. 0. 0. 0. 0. 1. 0. 0. 2. 1. 0.]
accuracy:
 0.9210526315789473
